# serverless.yml

service: triggersplus-x-peak

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-1

functions:
  app:
    handler: src/interface/token/createToken.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'